import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
import os
from dotenv import load_dotenv
load_dotenv()

def send_suspicion_email(login_message: str, recipient_email: str = "pigmancrazy@gmail.com"):
    """
    Sends a simple alert email to the hospital provider regarding login suspicion.

    Args:
        login_message (str): The message generated by the LLM indicating the type of login suspicion.
        recipient_email (str): Email address to send the alert to (default = 'pigmancrazy@gmail.com')
    """

    # ---- SMTP CONFIG ----
    SMTP_SERVER = "smtp.gmail.com"
    SMTP_PORT = 587
    SENDER_EMAIL = "keshavmukundan03@gmail.com"          
    SENDER_PASSWORD = os.getenv("GMAIL_APP_PASSWORD")   

    # ---- EMAIL CONTENT ----
    subject = "⚠️ Login Suspicion Alert - EHR Access Protection System"

    msg = MIMEMultipart()
    msg["From"] = SENDER_EMAIL
    msg["To"] = recipient_email
    msg["Subject"] = subject

    body = f"""
    ------------------------------------
    {login_message}
    ------------------------------------
    """

    msg.attach(MIMEText(body, "plain"))

    # ---- SEND MAIL ----
    try:
        with smtplib.SMTP(SMTP_SERVER, SMTP_PORT) as server:
            server.starttls()
            server.login(SENDER_EMAIL, SENDER_PASSWORD)
            server.send_message(msg)
            print("✅ Suspicion alert email sent successfully!")
    except Exception as e:
        print(f"❌ Failed to send email: {e}")
